### ISSUE TITLE
Slice timing unit 

### ISSUE THREAD

**Issue by ArCourtin** [CPernet/spmup#53]
Hi,

I think there is a unit problem in "spmup_BIDS_preprocess".
Slice timings are stored in s in the BIDS format and SPM uses slice timings in ms.
However, as far as I understand, the slice timings are not converted to ms by spmup.

Am I missing something?

Best wishes,
Arthur

**Comment by CPernet** [comment]
mmh indeed looks like https://github.com/CPernet/spmup/blob/master/bids/spmup_BIDS_preprocess.m#L233 needs *1000 (unless spm_BIDS have updated that info, in the subject structure,  I don't think so) @fishpm 
- yet I don't quite see why it works because https://github.com/spm/spm/blob/main/spm_slice_timing.m#L116 returns the correct info (I'd need to run it, but not logged onto the server - just answering to quick track/be on top of that)
